### ISSUE TITLE
Some missing solution.md files

### ISSUE THREAD

**Issue by abpolym** [IceCTF/Problems-2015#1]
Hey,

some of your `solution.md` files are just copies of other writeups/solution.md files instead of real writeups.

Can you add / create those?

See [this one](https://github.com/IceCTF/Problems-2015/blob/master/stage4/forensics/alien_contact/solution.md) for example.

**Comment by Glitch-is** [comment]
I suggest you go see the writeups the contestants have composed here https://github.com/ctfs/write-ups-2015/tree/master/icectf-2015
They go into way more detail and are more complete.

**Comment by abpolym** [comment]
@Glitch-is I am one of the maintainer/owner of this repo and asking, because I can't find any writeups for several challenges, e.g. the mentioned one :)

**Comment by Glitch-is** [comment]
Ah ok, cool. We will go through them and add those ;)

**Comment by Glitch-is** [comment]
@YASME-Tim 
Ok, I added the missing writeups (Alien contact and Mondrian)

You're welcome :D

**Comment by abpolym** [comment]
Thanks! :)

**Comment by abpolym** [comment]
@Glitch-is Just some question: What image editor did you use or in what format did you save the rave.gif frames for the epilepsy challenge? All I currently can do is three bmps by `convert rave.gif rave.bmp`, then import the bmp with the tv static-like pixels as raw data into `audacity` to get this:

![](https://transfer.sh/6FlNh/wtf.png)

But none of these channels sound good.

This is the frame I am talking about:

https://transfer.sh/6xSgI/rave-0.bmp

Can you help me? Thanks :)

**Comment by Glitch-is** [comment]
@YASME-Tim Yea, this problem was way more difficult than we intended, but you can watch us solve this problem https://youtu.be/gqAoCpUfXaI?t=22m5s
It's in Icelandic, but you should be able to see what we were doing.

Even when you got the audio it was still pretty hard to make out the words that you were suppose to hear

**Comment by abpolym** [comment]
@Glitch-is Ok thanks I'll have a look :)

**Comment by abpolym** [comment]
@Glitch-is I reproduced your solution [here](https://github.com/ctfs/write-ups-2015/tree/master/icectf-2015/forensics/epilepsy-warning), but can't really understand the words said by the robotic voice. Does it say anything in icelandic?

**Comment by Glitch-is** [comment]
@YASME-Tim No, it's in English... It's just a terrible speech engine that I shouldn't have put effects and stuff on :(

The voice says "The second part of the flag is hidden underscore audio"

I was going to make it easier in the middle of the competition, since people were complaining. but loads of teams had already solved it and it wouldn't have been fair to them.
